name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "*"

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.10"
          spec: "dcc.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "dcc"
          options: --onefile, --name "dcc", --windowed,
